import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {ThemeProvider} from "@/components/theme-provider";
import {VideoProvider} from "@/context/video-context";
import {AuthProvider} from "@/hooks/auth";
import {Toaster} from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <AuthProvider>
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute={"class"}
          forcedTheme={"dark"}
          storageKey={"gamehub-theme"}
        >
          <VideoProvider>
            <Toaster position="top-right" />
            {children}
          </VideoProvider>
        </ThemeProvider>
      </body>
    </AuthProvider>
    </html>
  );
}
